export default {
    darkMode: "class",
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    theme: {
        extend: {
            "colors": {
                "on-error": "#ffffff",
                "outline-variant": "#e2e8f0",
                "surface-container-high": "#f8fafc",
                "primary-fixed": "#f5f1ed",
                "outline": "#64748b",
                "on-secondary": "#ffffff",
                "background": "#ffffff",
                "surface": "#ffffff",
                "on-background": "#0f172a",
                "tertiary-container": "#f5f1ed",
                "on-primary": "#ffffff",
                "tertiary-fixed": "#f5f1ed",
                "on-secondary-fixed-variant": "#856b54",
                "primary": "#cfb095",
                "secondary-container": "#cfb095",
                "primary-fixed-dim": "#bca188",
                "surface-variant": "#ffffff",
                "tertiary-fixed-dim": "#bca188",
                "surface-dim": "#ffffff",
                "on-secondary-fixed": "#2c1e14",
                "on-secondary-container": "#ffffff",
                "inverse-on-surface": "#ffffff",
                "on-surface-variant": "#475569",
                "error": "#dc2626",
                "surface-container": "#ffffff",
                "secondary-fixed-dim": "#bca188",
                "secondary": "#cfb095",
                "on-tertiary-fixed": "#2c1e14",
                "on-primary-fixed": "#2c1e14",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#856b54",
                "surface-bright": "#ffffff",
                "on-tertiary-fixed-variant": "#856b54",
                "primary-container": "#cfb095",
                "inverse-surface": "#0f172a",
                "on-error-container": "#ffdad6",
                "surface-container-highest": "#e2e8f0",
                "tertiary": "#cfb095",
                "surface-tint": "#cfb095",
                "on-tertiary-container": "#2c1e14",
                "on-tertiary": "#ffffff",
                "error-container": "#fee2e2",
                "inverse-primary": "#f5f1ed",
                "surface-container-low": "#ffffff",
                "secondary-fixed": "#f5f1ed",
                "on-primary-container": "#ffffff",
                "on-surface": "#1e293b"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "2xl": "1rem",
                "3xl": "1.5rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"],
                "mono": ["JetBrains Mono", "monospace"]
            }
        }
    },
    plugins: [],
}
